// Literal port of dev/Code/CryEngine/CryCommon/IValidator.h (subset).
// Original Copyright Crytek GMBH or its affiliates, used under license.

namespace CryAISystem.CryCommon;

public enum EValidatorModule
{
    VALIDATOR_MODULE_UNKNOWN,
    VALIDATOR_MODULE_RENDERER,
    VALIDATOR_MODULE_3DENGINE,
    VALIDATOR_MODULE_ASSETS,
    VALIDATOR_MODULE_AI,
    VALIDATOR_MODULE_ANIMATION,
    VALIDATOR_MODULE_ENTITYSYSTEM,
    VALIDATOR_MODULE_SCRIPTSYSTEM,
    VALIDATOR_MODULE_SYSTEM,
    VALIDATOR_MODULE_AUDIO,
    VALIDATOR_MODULE_GAME,
    VALIDATOR_MODULE_MOVIE,
    VALIDATOR_MODULE_EDITOR,
    VALIDATOR_MODULE_NETWORK,
    VALIDATOR_MODULE_PHYSICS,
    VALIDATOR_MODULE_FLOWGRAPH,
    VALIDATOR_MODULE_ONLINE,
    VALIDATOR_MODULE_DRS,
    VALIDATOR_MODULE_FEATURETESTS,
    VALIDATOR_MODULE_SHINE,
}

public enum EValidatorSeverity
{
    VALIDATOR_ERROR,
    VALIDATOR_ERROR_DBGBRK,
    VALIDATOR_WARNING,
    VALIDATOR_COMMENT,
    VALIDATOR_ASSERT,
}

[System.Flags]
public enum EValidatorFlags
{
    VALIDATOR_FLAG_FILE = 1,
    VALIDATOR_FLAG_TEXTURE = 1 << 1,
    VALIDATOR_FLAG_AUDIO = 1 << 2,
    VALIDATOR_FLAG_AI = 1 << 3,
    VALIDATOR_FLAG_LOG_ASSET_SCOPE = 1 << 4,
    VALIDATOR_FLAG_IGNORE_IN_EDITOR = 1 << 5,
    VALIDATOR_FLAG_SCRIPT = 1 << 6,
}
