// Literal port of dev/Code/CryEngine/CryAISystem/AISignalCRCs.{h,cpp}
// Original Copyright Crytek GMBH or its affiliates, used under license.

using CryAISystem.CryCommon;

namespace CryAISystem;

public struct AISIGNALS_CRC
{
    //		AI actions order.
    private const string AIORD_ATTACK = "ORD_ATTACK";
    private const string AIORD_SEARCH = "ORD_SEARCH";
    private const string AIORD_REPORTDONE = "ORD_DONE";
    private const string AIORD_REPORTFAIL = "ORD_FAIL";

    //the ctor initializations are now moved into Init since the central crc generator access must be at a known time
    // AISIGNALS_CRC() — empty ctor; C# struct default-init handles fields.

    //initializes all crc dependent members, called in CAISystem ctor
    public void Init()
    {
        m_nOnRequestNewObstacle = CCrc32.Compute("OnRequestNewObstacle");
        m_nOnRequestUpdate = CCrc32.Compute("OnRequestUpdate");
        m_nOnRequestUpdateAlternative = CCrc32.Compute("OnRequestUpdateAlternative");
        m_nOnRequestUpdateTowards = CCrc32.Compute("OnRequestUpdateTowards");
        m_nOnClearSpotList = CCrc32.Compute("OnClearSpotList");
        m_nOnRequestShootSpot = CCrc32.Compute("OnRequestShootSpot");
        m_nOnRequestHideSpot = CCrc32.Compute("OnRequestHideSpot");
        m_nOnStartTimer = CCrc32.Compute("OnStartTimer");
        m_nOnLastKnownPositionApproached = CCrc32.Compute("OnLastKnownPositionApproached");
        m_nOnEndApproach = CCrc32.Compute("OnEndApproach");
        m_nOnAbortAction = CCrc32.Compute("OnAbortAction");
        m_nOnActionCompleted = CCrc32.Compute("OnActionCompleted");
        m_nOnNoPathFound = CCrc32.Compute("OnNoPathFound");
        m_nOnApproachEnd = CCrc32.Compute("OnApproachEnd");
        m_nOnEndFollow = CCrc32.Compute("OnEndFollow");
        m_nOnBulletRain = CCrc32.Compute("OnBulletRain");
        m_nOnBulletHit = CCrc32.Compute("OnBulletHit");
        m_nOnDriverEntered = CCrc32.Compute("OnDriverEntered");
        m_nOnCheckDeadTarget = CCrc32.Compute("OnCheckDeadTarget");
        m_nOnCheckDeadBody = CCrc32.Compute("OnCheckDeadBody");

        m_nAIORD_ATTACK = CCrc32.Compute(AIORD_ATTACK);
        m_nAIORD_SEARCH = CCrc32.Compute(AIORD_SEARCH);
        m_nAIORD_REPORTDONE = CCrc32.Compute(AIORD_REPORTDONE);
        m_nAIORD_REPORTFAIL = CCrc32.Compute(AIORD_REPORTFAIL);

        m_nOnChangeStance = CCrc32.Compute("OnChangeStance");
        m_nOnScaleFormation = CCrc32.Compute("OnScaleFormation");
        m_nOnUnitDied = CCrc32.Compute("OnUnitDied");
        m_nOnUnitDamaged = CCrc32.Compute("OnUnitDamaged");
        m_nOnUnitBusy = CCrc32.Compute("OnUnitBusy");
        m_nOnUnitSuspended = CCrc32.Compute("OnUnitSuspended");
        m_nOnUnitResumed = CCrc32.Compute("OnUnitResumed");
        m_nOnSetUnitProperties = CCrc32.Compute("OnSetUnitProperties");
        m_nOnJoinTeam = CCrc32.Compute("OnJoinTeam");
        m_nRPT_LeaderDead = CCrc32.Compute("RPT_LeaderDead");

        m_nOnSpotSeeingTarget = CCrc32.Compute("OnSpotSeeingTarget");
        m_nOnSpotLosingTarget = CCrc32.Compute("OnSpotLosingTarget");

        m_nOnFormationPointReached = CCrc32.Compute("OnFormationPointReached");
        m_nOnKeepEnabled = CCrc32.Compute("OnKeepEnabled");
        m_nOnActionDone = CCrc32.Compute("OnActionDone");
        m_nOnGroupAdvance = CCrc32.Compute("OnGroupAdvance");
        m_nOnGroupSeek = CCrc32.Compute("OnGroupSeek");
        m_nOnLeaderReadabilitySeek = CCrc32.Compute("OnLeaderReadabilitySeek");
        m_nAddDangerPoint = CCrc32.Compute("AddDangerPoint");
        m_nOnGroupCover = CCrc32.Compute("OnGroupCover");
        m_nOnLeaderReadabilityAlarm = CCrc32.Compute("OnLeaderReadabilityAlarm");
        m_nOnAdvanceTargetCompromised = CCrc32.Compute("OnAdvanceTargetCompromised");
        m_nOnGroupCohesionTest = CCrc32.Compute("OnGroupCohesionTest");
        m_nOnGroupTestReadabilityCohesion = CCrc32.Compute("OnGroupTestReadabilityCohesion");
        m_nOnGroupTestReadabilityAdvance = CCrc32.Compute("OnGroupTestReadabilityAdvance");
        m_nOnGroupAdvanceTest = CCrc32.Compute("OnGroupAdvanceTest");
        m_nOnLeaderReadabilityAdvanceLeft = CCrc32.Compute("OnLeaderReadabilityAdvanceLeft");
        m_nOnLeaderReadabilityAdvanceRight = CCrc32.Compute("OnLeaderReadabilityAdvanceRight");
        m_nOnLeaderReadabilityAdvanceForward = CCrc32.Compute("OnLeaderReadabilityAdvanceForward");
        m_nOnGroupTurnAmbient = CCrc32.Compute("OnGroupTurnAmbient");
        m_nOnGroupTurnAttack = CCrc32.Compute("OnGroupTurnAttack");
        m_nOnShapeEnabled = CCrc32.Compute("OnShapeEnabled");
        m_nOnShapeDisabled = CCrc32.Compute("OnShapeDisabled");
        m_nOnCloseContact = CCrc32.Compute("OnCloseContact");
        m_nOnTargetDead = CCrc32.Compute("OnTargetDead");
        m_nOnEndPathOffset = CCrc32.Compute("OnEndPathOffset");
        m_nOnPathFindAtStart = CCrc32.Compute("OnPathFindAtStart");
        m_nOnPathFound = CCrc32.Compute("OnPathFound");
        m_nOnBackOffFailed = CCrc32.Compute("OnBackOffFailed");
        m_nOnBadHideSpot = CCrc32.Compute("OnBadHideSpot");
        m_nOnCoverReached = CCrc32.Compute("OnCoverReached");
        m_nOnMovingToCover = CCrc32.Compute("OnMovingToCover");
        m_nOnMovingInCover = CCrc32.Compute("OnMovingInCover");
        m_nOnEnterCover = CCrc32.Compute("OnEnterCover");
        m_nOnLeaveCover = CCrc32.Compute("OnLeaveCover");
        m_nOnCoverCompromised = CCrc32.Compute("OnCoverCompromised");
        m_nOnHighCover = CCrc32.Compute("OnHighCover");
        m_nOnLowCover = CCrc32.Compute("OnLowCover");
        m_nOnNoAimPosture = CCrc32.Compute("OnNoAimPosture");
        m_nOnNoPeekPosture = CCrc32.Compute("OnNoPeekPosture");
        m_nOnTPSDestinationNotFound = CCrc32.Compute("OnTPSDestNotFound");
        m_nOnTPSDestinationFound = CCrc32.Compute("OnTPSDestFound");
        m_nOnTPSDestinationReached = CCrc32.Compute("OnTPSDestReached");
        m_nOnRightLean = CCrc32.Compute("OnRightLean");
        m_nOnLeftLean = CCrc32.Compute("OnLeftLean");
        m_nOnLowHideSpot = CCrc32.Compute("OnLowHideSpot");
        m_nOnChargeStart = CCrc32.Compute("OnChargeStart");
        m_nOnChargeHit = CCrc32.Compute("OnChargeHit");
        m_nOnChargeMiss = CCrc32.Compute("OnChargeMiss");
        m_nOnChargeBailOut = CCrc32.Compute("OnChargeBailOut");
        m_nORDER_IDLE = CCrc32.Compute("ORDER_IDLE");
        m_nOnNoGroupTarget = CCrc32.Compute("OnNoGroupTarget");
        m_nOnLeaderTooFar = CCrc32.Compute("OnLeaderTooFar");
        m_nOnEnemySteady = CCrc32.Compute("OnEnemySteady");
        m_nOnShootSpotFound = CCrc32.Compute("OnShootSpotFound");
        m_nOnShootSpotNotFound = CCrc32.Compute("OnShootSpotNotFound");
        m_nOnLeaderStop = CCrc32.Compute("OnLeaderStop");
        m_nOnUnitMoving = CCrc32.Compute("OnUnitMoving");
        m_nOnUnitStop = CCrc32.Compute("OnUnitStop");
        m_nORDER_EXIT_VEHICLE = CCrc32.Compute("ORDER_EXIT_VEHICLE");
        m_nOnNoFormationPoint = CCrc32.Compute("OnNoFormationPoint");
        m_nOnTargetApproaching = CCrc32.Compute("OnTargetApproaching");
        m_nOnTargetFleeing = CCrc32.Compute("OnTargetFleeing");
        m_nOnNoTargetVisible = CCrc32.Compute("OnNoTargetVisible");
        m_nOnNoTargetAwareness = CCrc32.Compute("OnNoTargetAwareness");
        m_nOnNoHidingPlace = CCrc32.Compute("OnNoHidingPlace");
        m_nOnLowAmmo = CCrc32.Compute("OnLowAmmo");
        m_nOnOutOfAmmo = CCrc32.Compute("OnOutOfAmmo");
        m_nOnReloaded = CCrc32.Compute("OnReloaded");
        m_nOnMeleeExecuted = CCrc32.Compute("OnMeleeExecuted");
        m_nOnPlayerLooking = CCrc32.Compute("OnPlayerLooking");
        m_nOnPlayerSticking = CCrc32.Compute("OnPlayerSticking");
        m_nOnPlayerLookingAway = CCrc32.Compute("OnPlayerLookingAway");
        m_nOnPlayerGoingAway = CCrc32.Compute("OnPlayerGoingAway");
        m_nOnTargetTooClose = CCrc32.Compute("OnTargetTooClose");
        m_nOnTargetTooFar = CCrc32.Compute("OnTargetTooFar");
        m_nOnFriendInWay = CCrc32.Compute("OnFriendInWay");
        m_nOnUseSmartObject = CCrc32.Compute("OnUseSmartObject");
        m_nOnAvoidDanger = CCrc32.Compute("OnAvoidDanger");
        m_nOnSetPredictionTime = CCrc32.Compute("m_nOnSetPredictionTime");
        m_nOnInterestSystemEvent = CCrc32.Compute("OnInterestSystemEvent");
        m_nOnSpecialAction = CCrc32.Compute("OnSpecialAction");
        m_nOnNewAttentionTarget = CCrc32.Compute("OnNewAttentionTarget");
        m_nOnAttentionTargetThreatChanged = CCrc32.Compute("OnAttentionTargetThreatChanged");
    }

    public uint32 m_nOnRequestNewObstacle;
    public uint32 m_nOnRequestUpdate;
    public uint32 m_nOnRequestShootSpot;
    public uint32 m_nOnRequestHideSpot;
    public uint32 m_nOnStartTimer;
    public uint32 m_nOnLastKnownPositionApproached;
    public uint32 m_nOnEndApproach;
    public uint32 m_nOnAbortAction;
    public uint32 m_nOnActionCompleted;
    public uint32 m_nOnNoPathFound;
    public uint32 m_nOnApproachEnd;
    public uint32 m_nOnEndFollow;
    public uint32 m_nOnBulletRain;
    public uint32 m_nOnBulletHit;
    public uint32 m_nOnDriverEntered;
    public uint32 m_nAIORD_ATTACK;
    public uint32 m_nAIORD_SEARCH;
    public uint32 m_nAIORD_REPORTDONE;
    public uint32 m_nAIORD_REPORTFAIL;
    public uint32 m_nOnChangeStance;
    public uint32 m_nOnScaleFormation;
    public uint32 m_nOnUnitDied;
    public uint32 m_nOnUnitDamaged;
    public uint32 m_nOnUnitBusy;
    public uint32 m_nOnUnitSuspended;
    public uint32 m_nOnUnitResumed;
    public uint32 m_nOnSetUnitProperties;
    public uint32 m_nOnJoinTeam;
    public uint32 m_nRPT_LeaderDead;
    public uint32 m_nOnSpotSeeingTarget;
    public uint32 m_nOnSpotLosingTarget;
    public uint32 m_nOnFormationPointReached;
    public uint32 m_nOnKeepEnabled;
    public uint32 m_nOnActionDone;
    public uint32 m_nOnGroupAdvance;
    public uint32 m_nOnGroupSeek;
    public uint32 m_nOnLeaderReadabilitySeek;
    public uint32 m_nOnGroupCover;
    public uint32 m_nAddDangerPoint;
    public uint32 m_nOnLeaderReadabilityAlarm;
    public uint32 m_nOnAdvanceTargetCompromised;
    public uint32 m_nOnGroupCohesionTest;
    public uint32 m_nOnGroupTestReadabilityCohesion;
    public uint32 m_nOnGroupTestReadabilityAdvance;
    public uint32 m_nOnGroupAdvanceTest;
    public uint32 m_nOnLeaderReadabilityAdvanceLeft;
    public uint32 m_nOnLeaderReadabilityAdvanceRight;
    public uint32 m_nOnLeaderReadabilityAdvanceForward;
    public uint32 m_nOnGroupTurnAmbient;
    public uint32 m_nOnGroupTurnAttack;
    public uint32 m_nOnShapeEnabled;
    public uint32 m_nOnShapeDisabled;
    public uint32 m_nOnCloseContact;
    public uint32 m_nOnTargetDead;
    public uint32 m_nOnEndPathOffset;
    public uint32 m_nOnPathFindAtStart;
    public uint32 m_nOnPathFound;
    public uint32 m_nOnBackOffFailed;
    public uint32 m_nOnBadHideSpot;
    public uint32 m_nOnCoverReached;
    public uint32 m_nOnTPSDestinationNotFound;
    public uint32 m_nOnTPSDestinationFound;
    public uint32 m_nOnTPSDestinationReached;
    public uint32 m_nOnRightLean;
    public uint32 m_nOnLeftLean;
    public uint32 m_nOnLowHideSpot;
    public uint32 m_nOnChargeStart;
    public uint32 m_nOnChargeHit;
    public uint32 m_nOnChargeMiss;
    public uint32 m_nOnChargeBailOut;
    public uint32 m_nOnMovingToCover;
    public uint32 m_nOnMovingInCover;
    public uint32 m_nOnEnterCover;
    public uint32 m_nOnLeaveCover;
    public uint32 m_nOnCoverCompromised;
    public uint32 m_nOnCoverLocationCompromised;
    public uint32 m_nOnHighCover;
    public uint32 m_nOnLowCover;
    public uint32 m_nOnNoAimPosture;
    public uint32 m_nOnNoPeekPosture;
    public uint32 m_nORDER_IDLE;
    public uint32 m_nOnNoGroupTarget;
    public uint32 m_nOnLeaderTooFar;
    public uint32 m_nOnEnemySteady;
    public uint32 m_nOnShootSpotFound;
    public uint32 m_nOnShootSpotNotFound;
    public uint32 m_nOnLeaderStop;
    public uint32 m_nOnUnitMoving;
    public uint32 m_nOnUnitStop;
    public uint32 m_nORDER_EXIT_VEHICLE;
    public uint32 m_nOnNoFormationPoint;
    public uint32 m_nOnTargetApproaching;
    public uint32 m_nOnTargetFleeing;
    public uint32 m_nOnNoTargetVisible;
    public uint32 m_nOnNoTargetAwareness;
    public uint32 m_nOnNoHidingPlace;
    public uint32 m_nOnLowAmmo;
    public uint32 m_nOnOutOfAmmo;
    public uint32 m_nOnReloaded;
    public uint32 m_nOnMeleeExecuted;
    public uint32 m_nOnPlayerLooking;
    public uint32 m_nOnPlayerSticking;
    public uint32 m_nOnPlayerLookingAway;
    public uint32 m_nOnPlayerGoingAway;
    public uint32 m_nOnTargetTooClose;
    public uint32 m_nOnTargetTooFar;
    public uint32 m_nOnFriendInWay;
    public uint32 m_nOnUseSmartObject;
    public uint32 m_nOnAvoidDanger;
    public uint32 m_nOnRequestUpdateTowards;
    public uint32 m_nOnRequestUpdateAlternative;
    public uint32 m_nOnClearSpotList;
    public uint32 m_nOnSetPredictionTime;
    public uint32 m_nOnInterestSystemEvent;
    public uint32 m_nOnCheckDeadTarget;
    public uint32 m_nOnCheckDeadBody;
    public uint32 m_nOnSpecialAction;
    public uint32 m_nOnNewAttentionTarget;
    public uint32 m_nOnAttentionTargetThreatChanged;
}
